#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later

# Local updater used by the standalone GX bootstrap installer.
#
# The updater can:
# - materialize or refresh a working repository tree under the target directory
# - preserve and additively merge the user-edited Venus config
# - validate the resulting config before activating a refreshed tree
# - keep versioned release directories and rollback pointers ready

set -eu

usage() {
	echo "Usage: $0 [--dry-run|--preview] <target-dir>" >&2
	exit 1
}

apply_resource_priority() {
	[ "${VENUS_EVCHARGER_RESOURCE_PRIORITY_APPLIED:-0}" = "1" ] && return 0
	export VENUS_EVCHARGER_RESOURCE_PRIORITY_APPLIED=1
	priority="${VENUS_EVCHARGER_UPDATER_NICE_LEVEL:-15}"
	if command -v ionice >/dev/null 2>&1 && command -v nice >/dev/null 2>&1 && ionice -c 3 true >/dev/null 2>&1; then
		exec ionice -c 3 nice -n "$priority" "$0" "$@"
	fi
	if command -v nice >/dev/null 2>&1; then
		exec nice -n "$priority" "$0" "$@"
	fi
}

apply_resource_priority "$@"

DRY_RUN=0
if [ "${1:-}" = "--dry-run" ] || [ "${1:-}" = "--preview" ]; then
	DRY_RUN=1
	shift
fi

if [ "${1:-}" = "" ] || [ "${2:-}" != "" ]; then
	usage
fi

TARGET_DIR="$1"
DEFAULT_REPO_SLUG="martinthebrain/venus-evcharger-service"
DEFAULT_CHANNEL="main"
REPO_SLUG="${VENUS_EVCHARGER_REPO_SLUG:-$DEFAULT_REPO_SLUG}"
CHANNEL="${VENUS_EVCHARGER_CHANNEL:-$DEFAULT_CHANNEL}"
SOURCE_DIR_OVERRIDE="${VENUS_EVCHARGER_SOURCE_DIR:-}"
SOURCE_COMMIT_OVERRIDE="${VENUS_EVCHARGER_SOURCE_COMMIT:-}"
MANIFEST_SOURCE="${VENUS_EVCHARGER_MANIFEST_SOURCE:-}"
if [ -n "${VENUS_EVCHARGER_MANIFEST_SIG_SOURCE:-}" ]; then
	MANIFEST_SIG_SOURCE="$VENUS_EVCHARGER_MANIFEST_SIG_SOURCE"
elif [ -n "$MANIFEST_SOURCE" ]; then
	MANIFEST_SIG_SOURCE="${MANIFEST_SOURCE}.sig"
else
	MANIFEST_SIG_SOURCE=""
fi
BOOTSTRAP_PUBKEY_OVERRIDE="${VENUS_EVCHARGER_BOOTSTRAP_PUBKEY:-}"
REQUIRE_SIGNED_MANIFEST="${VENUS_EVCHARGER_REQUIRE_SIGNED_MANIFEST:-0}"
ARCHIVE_URL_OVERRIDE="${VENUS_EVCHARGER_ARCHIVE_URL:-}"
ARCHIVE_URL="${ARCHIVE_URL_OVERRIDE:-https://codeload.github.com/${REPO_SLUG}/tar.gz/refs/heads/${CHANNEL}}"
SOURCE_REF_URL="${VENUS_EVCHARGER_SOURCE_REF_URL:-https://api.github.com/repos/${REPO_SLUG}/commits/${CHANNEL}}"
DOWNLOAD_TIMEOUT_SECONDS="${VENUS_EVCHARGER_DOWNLOAD_TIMEOUT_SECONDS:-60}"
DOWNLOAD_ATTEMPTS="${VENUS_EVCHARGER_DOWNLOAD_ATTEMPTS:-2}"
STATE_DIR="${TARGET_DIR}/.bootstrap-state"
WORK_ROOT_OVERRIDE="${VENUS_EVCHARGER_UPDATER_WORK_ROOT:-}"
WORK_ROOT=""
WORK_STORAGE=""
FALLBACK_WORK_ROOT="${STATE_DIR}/work"
RAM_WORK_BASE="${VENUS_EVCHARGER_UPDATER_RAM_WORK_BASE:-${TMPDIR:-/tmp}}"
RAM_MIN_MEM_AVAILABLE_KB="${VENUS_EVCHARGER_UPDATER_RAM_MIN_MEM_AVAILABLE_KB:-393216}"
RAM_MIN_FILESYSTEM_AVAILABLE_KB="${VENUS_EVCHARGER_UPDATER_RAM_MIN_FILESYSTEM_AVAILABLE_KB:-196608}"
SD_WORK_ROOT_OVERRIDE="${VENUS_EVCHARGER_UPDATER_SD_WORK_ROOT:-}"
MOUNTS_PATH="${VENUS_EVCHARGER_UPDATER_MOUNTS_PATH:-/proc/mounts}"
UPDATE_LOCK_DIR="${STATE_DIR}/update.lock"
RESOURCE_GUARD_ENABLED="${VENUS_EVCHARGER_UPDATER_RESOURCE_GUARD:-1}"
RESOURCE_WAIT_SECONDS="${VENUS_EVCHARGER_UPDATER_RESOURCE_WAIT_SECONDS:-120}"
RESOURCE_POLL_SECONDS="${VENUS_EVCHARGER_UPDATER_RESOURCE_POLL_SECONDS:-1}"
RESOURCE_MAX_LOAD1="${VENUS_EVCHARGER_UPDATER_MAX_LOAD1:-8.0}"
RESOURCE_MAX_LOAD5="${VENUS_EVCHARGER_UPDATER_MAX_LOAD5:-7.0}"
RESOURCE_MAX_LOAD15="${VENUS_EVCHARGER_UPDATER_MAX_LOAD15:-5.0}"
RESOURCE_MIN_MEM_AVAILABLE_KB="${VENUS_EVCHARGER_UPDATER_MIN_MEM_AVAILABLE_KB:-65536}"
RESOURCE_MIN_DISK_AVAILABLE_KB="${VENUS_EVCHARGER_UPDATER_MIN_DISK_AVAILABLE_KB:-131072}"
RESOURCE_LOADAVG_PATH="${VENUS_EVCHARGER_UPDATER_LOADAVG_PATH:-/proc/loadavg}"
RESOURCE_MEMINFO_PATH="${VENUS_EVCHARGER_UPDATER_MEMINFO_PATH:-/proc/meminfo}"
INSTALLED_BUNDLE_HASH_FILE="${STATE_DIR}/installed_bundle_sha256"
INSTALLED_VERSION_FILE="${STATE_DIR}/installed_version"
INSTALLED_SOURCE_COMMIT_FILE="${STATE_DIR}/installed_source_commit"
DEPLOYMENT_RECEIPT_FILE="${STATE_DIR}/deployment_receipt.json"
BOOTSTRAP_ENTRYPOINT="${VENUS_EVCHARGER_BOOTSTRAP_ENTRYPOINT:-}"
STATUS_FILE="${STATE_DIR}/update_status.json"
AUDIT_LOG_FILE="${STATE_DIR}/update_audit.log"
RELEASES_DIR="${TARGET_DIR}/releases"
CURRENT_LINK="${TARGET_DIR}/current"
PREVIOUS_LINK="${TARGET_DIR}/previous"
TMP_DIR=""

RUN_MODE="apply"
[ "$DRY_RUN" = "1" ] && RUN_MODE="dry-run"
RUN_RESULT="failed"
RUN_FAILURE_REASON=""
RUN_OLD_VERSION=""
RUN_NEW_VERSION=""
RUN_OLD_BUNDLE_SHA256=""
RUN_NEW_BUNDLE_SHA256=""
RUN_OLD_SOURCE_COMMIT=""
RUN_NEW_SOURCE_COMMIT=""
CURRENT_PRESERVED=0
CURRENT_ALREADY_MATCHED=0
PROMOTED_RELEASE=""
PROMOTION_ABORTED_REASON=""
ROLLBACK_REASON=""
VALIDATION_PASSED=0
CONFIG_VALIDATION_MODE="not-run"
CONFIG_MERGE_CHANGED=0
CONFIG_MERGE_COMMENT_PRESERVED=1
CONFIG_MERGE_SKIPPED_REASON=""
CONFIG_MERGE_BACKUP_PATH=""
CONFIG_MERGE_BACKUP_REQUIRED=0
CONFIG_SCHEMA_BEFORE=""
CONFIG_SCHEMA_TARGET=""
CONFIG_MERGE_ADDED_KEYS=""
CONFIG_MERGE_ADDED_SECTIONS=""
CONFIG_MIGRATIONS_APPLIED=""
BOOTSTRAP_REFRESHED=0
UPDATE_LOCK_HELD=0

export TARGET_DIR RUN_MODE RUN_RESULT RUN_FAILURE_REASON
export RUN_OLD_VERSION RUN_NEW_VERSION RUN_OLD_BUNDLE_SHA256 RUN_NEW_BUNDLE_SHA256
export RUN_OLD_SOURCE_COMMIT RUN_NEW_SOURCE_COMMIT REPO_SLUG CHANNEL DEPLOYMENT_RECEIPT_FILE
export BOOTSTRAP_ENTRYPOINT BOOTSTRAP_REFRESHED
export CURRENT_PRESERVED CURRENT_ALREADY_MATCHED PROMOTED_RELEASE PROMOTION_ABORTED_REASON ROLLBACK_REASON
export VALIDATION_PASSED CONFIG_VALIDATION_MODE
export CONFIG_MERGE_CHANGED CONFIG_MERGE_COMMENT_PRESERVED CONFIG_MERGE_SKIPPED_REASON
export CONFIG_MERGE_BACKUP_PATH CONFIG_MERGE_BACKUP_REQUIRED CONFIG_SCHEMA_BEFORE CONFIG_SCHEMA_TARGET
export CONFIG_MERGE_ADDED_KEYS CONFIG_MERGE_ADDED_SECTIONS CONFIG_MIGRATIONS_APPLIED
export WORK_ROOT WORK_STORAGE UPDATE_LOCK_DIR

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" >/dev/null 2>&1 && pwd)
UPDATER_LIB_DIR="${SCRIPT_DIR}/bootstrap_updater.d"
for lib_name in 00_core.sh 10_config_merge.sh 20_layout.sh 30_status_main.sh; do
	# shellcheck source=/dev/null
	. "${UPDATER_LIB_DIR}/${lib_name}"
done

main
