from typing import Protocol

class _MainLoop(Protocol):
    def run(self) -> None: ...
    def quit(self) -> None: ...

class _GLib:
    def MainLoop(self) -> _MainLoop: ...
    def timeout_add(self, interval: int, callback: object) -> int: ...
    def idle_add(self, callback: object) -> int: ...

GLib: _GLib
