# SPDX-License-Identifier: GPL-3.0-or-later
from tests.test_branch_coverage_hotspots_support import *  # noqa: F401,F403
from tests.test_branch_coverage_hotspots_part1 import _BranchCoverageWizardEnergyCasesPart1
from tests.test_branch_coverage_hotspots_part2 import _BranchCoverageVictronLearningCasesPart1
from tests.test_branch_coverage_hotspots_part3 import _BranchCoverageVictronApplyCasesPart1
from tests.test_branch_coverage_hotspots_part4 import _BranchCoverageVictronApplyCasesPart2
from tests.test_branch_coverage_hotspots_part5 import _BranchCoverageVictronTelemetryCasesPart1
from tests.test_branch_coverage_hotspots_part6 import _BranchCoverageWizardRenderCasesPart1
from tests.test_branch_coverage_hotspots_part7 import _BranchCoverageVictronAdaptiveCasesPart1
from tests.test_branch_coverage_hotspots_part8 import _BranchCoverageVictronRecommendationCasesPart1
from tests.test_branch_coverage_hotspots_part9 import _BranchCoverageVictronSafetyCasesPart1

class BranchCoverageWizardEnergyCases(_BranchCoverageWizardEnergyCasesPart1, unittest.TestCase):
    pass

class BranchCoverageVictronLearningCases(_BranchCoverageVictronLearningCasesPart1, unittest.TestCase):
    pass

class BranchCoverageVictronApplyCases(_BranchCoverageVictronApplyCasesPart1, _BranchCoverageVictronApplyCasesPart2, unittest.TestCase):
    pass

class BranchCoverageVictronTelemetryCases(_BranchCoverageVictronTelemetryCasesPart1, unittest.TestCase):
    pass

class BranchCoverageWizardRenderCases(_BranchCoverageWizardRenderCasesPart1, unittest.TestCase):
    pass

class BranchCoverageVictronAdaptiveCases(_BranchCoverageVictronAdaptiveCasesPart1, unittest.TestCase):
    pass

class BranchCoverageVictronRecommendationCases(_BranchCoverageVictronRecommendationCasesPart1, unittest.TestCase):
    pass

class BranchCoverageVictronSafetyCases(_BranchCoverageVictronSafetyCasesPart1, unittest.TestCase):
    pass
