# SPDX-License-Identifier: GPL-3.0-or-later
from tests.test_venus_evcharger_setup_wizard_extensions_support import *  # noqa: F401,F403
from tests.test_venus_evcharger_setup_wizard_extensions_part1 import _TestShellyWallboxSetupWizardExtensionsPart1
from tests.test_venus_evcharger_setup_wizard_extensions_part2 import _TestShellyWallboxSetupWizardExtensionsPart2

class TestShellyWallboxSetupWizardExtensions(_TestShellyWallboxSetupWizardExtensionsPart1, _TestShellyWallboxSetupWizardExtensionsPart2, _TestShellyWallboxSetupWizardExtensionsHelperRole, unittest.TestCase):
    pass
