# SPDX-License-Identifier: GPL-3.0-or-later
from __future__ import annotations

from collections import deque
from types import SimpleNamespace
from typing import Any
from unittest.mock import MagicMock

from venus_evcharger.auto.policy import AutoPolicy, AutoStopEwmaPolicy, AutoThresholdProfile


def make_auto_metrics(**overrides: object) -> dict[str, object]:
    metrics: dict[str, object] = {
        "state": "waiting",
        "surplus": 850.0,
        "grid": -900.0,
        "soc": 55.0,
        "profile": "normal",
        "start_threshold": 1850.0,
        "stop_threshold": 1350.0,
        "learned_charge_power": None,
        "learned_charge_power_state": "unknown",
        "threshold_scale": 1.0,
        "threshold_mode": "static",
    }
    metrics.update(overrides)
    return metrics


def make_auto_policy(**overrides: object) -> AutoPolicy:
    policy = AutoPolicy(
        normal_profile=AutoThresholdProfile(2000.0, 1600.0),
        high_soc_profile=AutoThresholdProfile(1650.0, 800.0),
        high_soc_threshold=50.0,
        high_soc_release_threshold=45.0,
        min_soc=40.0,
        resume_soc=50.0,
        start_max_grid_import_watts=50.0,
        stop_grid_import_watts=300.0,
        grid_recovery_start_seconds=10.0,
        stop_surplus_delay_seconds=90.0,
        ewma=AutoStopEwmaPolicy(
            base_alpha=0.25,
            stable_alpha=0.55,
            volatile_alpha=0.15,
            volatility_low_watts=150.0,
            volatility_high_watts=400.0,
        ),
    )
    for name, value in overrides.items():
        setattr(policy, name, value)
    return policy


def make_auto_controller_service(**overrides: object) -> SimpleNamespace:
    data: dict[str, object] = {
        "auto_policy": make_auto_policy(),
        "auto_samples": deque(),
        "auto_average_window_seconds": 30.0,
        "relay_last_changed_at": None,
        "relay_last_off_at": None,
        "auto_min_runtime_seconds": 300.0,
        "auto_min_offtime_seconds": 120.0,
        "auto_allow_without_battery_soc": False,
        "auto_battery_scan_interval_seconds": 60.0,
        "auto_shelly_soft_fail_seconds": 10.0,
        "auto_night_lock_stop": False,
        "auto_stop_delay_seconds": 30.0,
        "auto_battery_discharge_balance_policy_enabled": False,
        "auto_battery_discharge_balance_warn_error_watts": 500.0,
        "auto_battery_discharge_balance_bias_start_error_watts": 750.0,
        "auto_battery_discharge_balance_bias_max_penalty_watts": 300.0,
        "auto_battery_discharge_balance_bias_mode": "always",
        "auto_battery_discharge_balance_bias_reserve_margin_soc": 5.0,
        "auto_battery_discharge_balance_coordination_enabled": False,
        "auto_battery_discharge_balance_coordination_support_mode": "supported_only",
        "auto_battery_discharge_balance_coordination_start_error_watts": 1000.0,
        "auto_battery_discharge_balance_coordination_max_penalty_watts": 200.0,
        "auto_contactor_fault_latch_count": 3,
        "auto_contactor_fault_latch_seconds": 60.0,
        "auto_start_delay_seconds": 10.0,
        "virtual_autostart": 1,
        "virtual_enable": 1,
        "virtual_mode": 1,
        "started_at": 0.0,
        "auto_startup_warmup_seconds": 0.0,
        "manual_override_until": 0.0,
        "auto_daytime_only": False,
        "auto_month_windows": {},
        "auto_scheduled_enabled_days": "Mon,Tue,Wed,Thu,Fri",
        "auto_scheduled_night_start_delay_seconds": 3600.0,
        "auto_scheduled_latest_end_time": "06:30",
        "auto_scheduled_night_current_amps": 0.0,
        "_last_auto_metrics": {},
        "_last_health_reason": "init",
        "_last_health_code": 0,
        "_last_auto_state": "idle",
        "_last_auto_state_code": 0,
        "backend_mode": "combined",
        "meter_backend_type": "shelly_combined",
        "switch_backend_type": "shelly_combined",
        "charger_backend_type": None,
        "_last_charger_state_enabled": None,
        "_last_charger_state_current_amps": None,
        "_last_charger_state_phase_selection": None,
        "_last_charger_state_actual_current_amps": None,
        "_last_charger_state_power_w": None,
        "_last_charger_state_energy_kwh": None,
        "_last_charger_state_status": None,
        "_last_charger_state_fault": None,
        "_last_charger_state_at": None,
        "_last_charger_transport_reason": None,
        "_last_charger_transport_source": None,
        "_last_charger_transport_detail": None,
        "_last_charger_transport_at": None,
        "_charger_retry_reason": None,
        "_charger_retry_source": None,
        "_charger_retry_until": None,
        "_charger_target_current_amps": None,
        "_charger_target_current_applied_at": None,
        "_phase_switch_mismatch_counts": {},
        "_phase_switch_last_mismatch_selection": None,
        "_phase_switch_last_mismatch_at": None,
        "_phase_switch_lockout_selection": None,
        "_phase_switch_lockout_reason": "",
        "_phase_switch_lockout_at": None,
        "_phase_switch_lockout_until": None,
        "_contactor_fault_counts": {},
        "_contactor_fault_active_reason": None,
        "_contactor_fault_active_since": None,
        "_contactor_lockout_reason": "",
        "_contactor_lockout_source": "",
        "_contactor_lockout_at": None,
        "time_now": lambda: 1000.0,
        "_last_battery_allow_warning": None,
        "_grid_recovery_required": False,
        "_grid_recovery_since": None,
        "_auto_high_soc_profile_active": None,
        "_auto_phase_target_candidate": None,
        "_auto_phase_target_since": None,
        "learned_charge_power_watts": None,
        "learned_charge_power_updated_at": None,
        "learned_charge_power_state": "unknown",
        "learned_charge_power_learning_since": None,
        "learned_charge_power_sample_count": 0,
        "learned_charge_power_phase": None,
        "learned_charge_power_voltage": None,
        "learned_charge_power_signature_mismatch_sessions": 0,
        "learned_charge_power_signature_checked_session_started_at": None,
        "_stop_smoothed_surplus_power": None,
        "_stop_smoothed_grid_power": None,
        "_auto_mode_cutover_pending": False,
        "_ignore_min_offtime_once": False,
        "auto_start_condition_since": None,
        "auto_stop_condition_since": None,
        "auto_stop_condition_reason": None,
        "auto_audit_log": False,
        "runtime": SimpleNamespace(
            pending_relay_command=MagicMock(return_value=(None, None)),
            warning_throttled=MagicMock(),
            write_auto_audit_event=MagicMock(),
        ),
        "state": SimpleNamespace(save_runtime_state=MagicMock()),
    }
    data.update(overrides)
    return SimpleNamespace(**data)


def make_runtime_support_service(**overrides: object) -> SimpleNamespace:
    data: dict[str, object] = {
        "poll_interval_ms": 1000,
        "deviceinstance": 60,
        "time_now": lambda: 1000.0,
        "_state_summary": lambda: "state",
        "_reset_system_bus": MagicMock(),
        "_invalidate_auto_pv_services": MagicMock(),
        "_invalidate_auto_battery_service": MagicMock(),
        "_ensure_observability_state": MagicMock(),
        "auto_audit_log": True,
        "auto_audit_log_path": "",
        "auto_audit_log_max_age_hours": 168.0,
        "auto_audit_log_repeat_seconds": 30.0,
        "_last_auto_audit_key": None,
        "_last_auto_audit_event_at": None,
        "_last_auto_audit_cleanup_at": 0.0,
        "_last_auto_state": "idle",
        "_last_auto_state_code": 0,
        "_last_pm_status": {"output": False},
        "_last_pm_status_confirmed": False,
        "_last_confirmed_pm_status": None,
        "_last_confirmed_pm_status_at": None,
        "_last_charger_transport_reason": None,
        "_last_charger_transport_source": None,
        "_last_charger_transport_detail": None,
        "_last_charger_transport_at": None,
        "_charger_retry_reason": None,
        "_charger_retry_source": None,
        "_charger_retry_until": None,
        "virtual_startstop": 0,
        "virtual_mode": 1,
        "virtual_enable": 1,
        "virtual_autostart": 1,
        "_last_auto_metrics": make_auto_metrics(),
        "auto_watchdog_stale_seconds": 10.0,
        "started_at": 0.0,
        "_last_successful_update_at": None,
        "auto_watchdog_recovery_seconds": 60.0,
        "auto_shelly_soft_fail_seconds": 10.0,
        "auto_contactor_fault_latch_count": 3,
        "auto_contactor_fault_latch_seconds": 60.0,
        "_last_recovery_attempt_at": None,
        "_recovery_attempts": 0,
        "relay_sync_timeout_seconds": 3.0,
        "_relay_sync_expected_state": None,
        "_relay_sync_requested_at": None,
        "_relay_sync_deadline_at": None,
        "_relay_sync_failure_reported": False,
        "_phase_switch_lockout_selection": None,
        "_phase_switch_lockout_reason": "",
        "_phase_switch_lockout_at": None,
        "_phase_switch_lockout_until": None,
        "_contactor_fault_counts": {},
        "_contactor_fault_active_reason": None,
        "_contactor_fault_active_since": None,
        "_contactor_lockout_reason": "",
        "_contactor_lockout_source": "",
        "_contactor_lockout_at": None,
        "auto_energy_sources": (),
        "auto_battery_discharge_balance_victron_bias_source_id": "",
        "auto_battery_discharge_balance_victron_bias_activation_mode": "always",
        "auto_battery_discharge_balance_victron_bias_kp": 0.0,
        "auto_battery_discharge_balance_victron_bias_ki": 0.0,
        "auto_battery_discharge_balance_victron_bias_kd": 0.0,
        "auto_battery_discharge_balance_victron_bias_deadband_watts": 0.0,
        "auto_battery_discharge_balance_victron_bias_max_abs_watts": 0.0,
        "auto_battery_discharge_balance_victron_bias_ramp_rate_watts_per_second": 0.0,
        "_victron_ess_balance_learning_profiles": {},
        "_victron_ess_balance_auto_apply_generation": 0,
    }
    data.update(overrides)
    return SimpleNamespace(**data)


def make_state_validation_service(**overrides: object) -> SimpleNamespace:
    data: dict[str, object] = {
        "auto_policy": AutoPolicy(),
        "poll_interval_ms": 200,
        "sign_of_life_minutes": 2,
        "auto_pv_max_services": 2,
        "auto_pv_scan_interval_seconds": 1.0,
        "auto_battery_scan_interval_seconds": 1.0,
        "auto_dbus_backoff_base_seconds": 1.0,
        "auto_dbus_backoff_max_seconds": 1.0,
        "auto_grid_missing_stop_seconds": 1.0,
        "auto_average_window_seconds": 1.0,
        "auto_min_runtime_seconds": 1.0,
        "auto_min_offtime_seconds": 1.0,
        "auto_start_delay_seconds": 1.0,
        "auto_stop_delay_seconds": 1.0,
        "auto_input_cache_seconds": 1.0,
        "auto_input_helper_restart_seconds": 1.0,
        "auto_input_helper_stale_seconds": 1.0,
        "auto_shelly_soft_fail_seconds": 1.0,
        "auto_watchdog_stale_seconds": 1.0,
        "auto_watchdog_recovery_seconds": 1.0,
        "auto_startup_warmup_seconds": 1.0,
        "auto_manual_override_seconds": 1.0,
        "auto_battery_discharge_balance_warn_error_watts": 1.0,
        "auto_battery_discharge_balance_bias_start_error_watts": 1.0,
        "auto_battery_discharge_balance_bias_max_penalty_watts": 1.0,
        "auto_battery_discharge_balance_bias_mode": "always",
        "auto_battery_discharge_balance_bias_reserve_margin_soc": 1.0,
        "auto_battery_discharge_balance_coordination_start_error_watts": 1.0,
        "auto_battery_discharge_balance_coordination_max_penalty_watts": 1.0,
        "auto_battery_discharge_balance_coordination_support_mode": "supported_only",
        "auto_scheduled_night_start_delay_seconds": 1.0,
        "auto_scheduled_night_current_amps": 0.0,
        "auto_scheduled_enabled_days": "Mon,Tue,Wed,Thu,Fri",
        "auto_scheduled_latest_end_time": "06:30",
        "auto_contactor_fault_latch_count": 1,
        "auto_contactor_fault_latch_seconds": 1.0,
        "shelly_request_timeout_seconds": 1.0,
        "dbus_method_timeout_seconds": 1.0,
    }
    data.update(overrides)
    return SimpleNamespace(**data)


def make_runtime_state_service(**overrides: object) -> SimpleNamespace:
    data: dict[str, Any] = {
        "time_now": lambda: 1000.0,
        "runtime_state_path": "",
        "virtual_mode": 1,
        "virtual_autostart": 1,
        "virtual_enable": 1,
        "virtual_startstop": 0,
        "manual_override_until": 0.0,
        "_auto_mode_cutover_pending": False,
        "_ignore_min_offtime_once": False,
        "learned_charge_power_watts": None,
        "learned_charge_power_updated_at": None,
        "learned_charge_power_state": "unknown",
        "learned_charge_power_learning_since": None,
        "learned_charge_power_sample_count": 0,
        "learned_charge_power_phase": None,
        "learned_charge_power_voltage": None,
        "learned_charge_power_signature_mismatch_sessions": 0,
        "learned_charge_power_signature_checked_session_started_at": None,
        "supported_phase_selections": ("P1",),
        "requested_phase_selection": "P1",
        "active_phase_selection": "P1",
        "relay_last_changed_at": None,
        "relay_last_off_at": None,
        "_runtime_state_serialized": None,
        "_last_health_reason": "init",
        "backend_mode": "combined",
        "meter_backend_type": "shelly_combined",
        "switch_backend_type": "shelly_combined",
        "charger_backend_type": None,
        "_last_charger_state_enabled": None,
        "_last_charger_state_current_amps": None,
        "_last_charger_state_phase_selection": None,
        "_last_charger_state_actual_current_amps": None,
        "_last_charger_state_power_w": None,
        "_last_charger_state_energy_kwh": None,
        "_last_charger_state_status": None,
        "_last_charger_state_fault": None,
        "_last_charger_state_at": None,
        "_charger_target_current_amps": None,
        "_phase_switch_mismatch_counts": {},
        "_phase_switch_last_mismatch_selection": None,
        "_phase_switch_last_mismatch_at": None,
        "_phase_switch_lockout_selection": None,
        "_phase_switch_lockout_reason": "",
        "_phase_switch_lockout_at": None,
        "_phase_switch_lockout_until": None,
        "_contactor_fault_counts": {},
        "_contactor_fault_active_reason": None,
        "_contactor_fault_active_since": None,
        "_contactor_lockout_reason": "",
        "_contactor_lockout_source": "",
        "_contactor_lockout_at": None,
    }
    data.update(overrides)
    return SimpleNamespace(**data)
