# SPDX-License-Identifier: GPL-3.0-or-later
"""Typed collaboration contracts for runtime support components."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol

from venus_evcharger.control import ControlCommand

AgeSeconds = Callable[[float | int | None, float | int | None], int]
HealthCode = Callable[[str], int]
DefaultFactory = Callable[[], Any]
WorkerSnapshot = dict[str, Any]


class AsyncRuntimeStatePort(Protocol):  # pragma: no cover - declarative typing contract
    """Initialize RAM-only async runtime state."""

    def initialize(self) -> None: ...


class ControlCommandQueuePort(Protocol):  # pragma: no cover - declarative typing contract
    """Queue and drain serialized control commands."""

    def enqueue(self, command: ControlCommand) -> bool: ...

    def drain_once(self) -> bool: ...


class MainloopWatchdogPort(Protocol):  # pragma: no cover - declarative typing contract
    """Maintain the GLib heartbeat."""

    def heartbeat_tick(self) -> bool: ...

    def start(self) -> None: ...


class RuntimeStateStorePort(Protocol):  # pragma: no cover - declarative typing contract
    """Own runtime defaults and atomic worker snapshots."""

    def worker_defaults(self) -> dict[str, DefaultFactory]: ...

    def observability_defaults(self) -> dict[str, DefaultFactory]: ...

    def ensure_worker_state(self) -> None: ...

    def ensure_observability_state(self) -> None: ...

    def set_worker_snapshot(self, snapshot: WorkerSnapshot) -> None: ...

    def update_worker_snapshot(self, **fields: Any) -> None: ...

    def get_worker_snapshot(self) -> WorkerSnapshot: ...


class AuditFieldsPort(Protocol):  # pragma: no cover - declarative typing contract
    """Provide normalized runtime fields to the audit logger."""

    def backend_value(self, svc: Any, attribute_name: str, default: str) -> str: ...

    def charger_target(self, svc: Any) -> float | None: ...

    def charger_transport_reason(self, svc: Any) -> str | None: ...

    def charger_transport_source(self, svc: Any) -> str | None: ...

    def charger_retry_reason(self, svc: Any) -> str | None: ...

    def charger_retry_source(self, svc: Any) -> str | None: ...

    def observed_phase(self, svc: Any) -> str | None: ...

    def phase_mismatch_active(self, svc: Any) -> bool: ...

    def callable_time_or_none(self, time_func: Any) -> float | None: ...

    def phase_lockout_active(self, svc: Any) -> bool: ...

    def phase_lockout_target(self, svc: Any) -> str | None: ...

    def phase_supported_effective(self, svc: Any) -> str: ...

    def phase_degraded_active(self, svc: Any) -> bool: ...

    def switch_feedback_closed(self, svc: Any) -> bool | None: ...

    def switch_interlock_ok(self, svc: Any) -> bool | None: ...

    def switch_feedback_mismatch(self, svc: Any) -> bool: ...

    def contactor_lockout_reason(self, svc: Any) -> str | None: ...

    def contactor_lockout_active(self, svc: Any) -> bool: ...

    def contactor_fault_count(self, svc: Any) -> int: ...

    def evse_fault_reason(self, svc: Any) -> str | None: ...

    def evse_fault_active(self, svc: Any) -> bool: ...

    def recovery_active(self, svc: Any) -> bool: ...
