# SPDX-License-Identifier: GPL-3.0-or-later
"""Controller ports owned by the wallbox service composition layer."""

from __future__ import annotations

import configparser
from collections.abc import Callable, Mapping
from typing import Protocol

from venus_evcharger.backend.shelly_io_types import (
    JsonObject,
    PendingRelayCommand,
    ShellyHttpSession,
    ShellyPmStatus,
    ShellyRpcScalar,
)
from venus_evcharger.bootstrap.contracts import MonthWindow
from venus_evcharger.control import ControlCommand, ControlResult
from venus_evcharger.control.models import ControlCommandName, ControlCommandSource
from venus_evcharger.runtime.contracts import WorkerSnapshot

PhaseData = dict[str, dict[str, float]]
PhaseValues = Callable[[float | int, float | int, str, str], PhaseData]


class ServiceFunctionsPort(Protocol):
    """Pure functions and platform values exposed by the composition owner."""

    @property
    def normalize_phase(self) -> Callable[[object], str]: ...
    @property
    def normalize_mode(self) -> Callable[[object], int]: ...
    @property
    def mode_uses_auto_logic(self) -> Callable[[object], bool]: ...
    @property
    def month_window(self) -> MonthWindow: ...
    @property
    def age_seconds(self) -> Callable[[float | int | None, float | int | None], int]: ...
    @property
    def health_code(self) -> Callable[[str], int]: ...
    @property
    def phase_values(self) -> PhaseValues: ...
    @property
    def read_version(self) -> Callable[[str], str]: ...
    @property
    def gobject(self) -> object: ...
    @property
    def script_path(self) -> str: ...
    @property
    def config_path(self) -> str: ...
    @property
    def auto_input_helper_path(self) -> str: ...


class AutoControllerPort(Protocol):
    def clear_auto_samples(self) -> None: ...
    def mark_relay_changed(self, relay_on: bool, now: float | None = None) -> None: ...
    def set_health(self, reason: str, cached: bool = False) -> None: ...
    def auto_decide_relay(
        self,
        relay_on: bool,
        pv_power: float | None,
        battery_soc: float | int | None,
        grid_power: float | None,
    ) -> bool: ...


class WriteControllerPort(Protocol):
    def build_control_command(
        self,
        name: ControlCommandName,
        target: str,
        value: object,
        *,
        source: ControlCommandSource = "internal",
    ) -> ControlCommand: ...

    def build_control_command_from_payload(
        self,
        payload: dict[str, object],
        *,
        source: ControlCommandSource = "http",
    ) -> ControlCommand: ...

    def handle_control_command(self, command: ControlCommand) -> ControlResult: ...


class AutoInputControllerPort(Protocol):
    def stop_helper(self, force: bool = False) -> None: ...
    def spawn_helper(self, now: float | None = None) -> None: ...
    def ensure_helper_process(self, now: float | None = None) -> None: ...
    def refresh_snapshot(self, now: float | None = None) -> None: ...


class RuntimeControllerPort(Protocol):
    def init_worker_state(self) -> None: ...
    def ensure_worker_state(self) -> None: ...
    def start_update_worker(self) -> None: ...
    def schedule_update_cycle(self) -> bool: ...
    def start_control_command_worker(self) -> None: ...
    def enqueue_control_command(self, command: ControlCommand) -> bool: ...
    def mainloop_heartbeat_tick(self) -> bool: ...
    def start_mainloop_watchdog(self) -> None: ...
    def update_worker_snapshot(self, **fields: object) -> None: ...
    def get_worker_snapshot(self) -> WorkerSnapshot: ...
    def ensure_observability_state(self) -> None: ...
    def is_update_stale(self, now: float | None = None) -> bool: ...
    def watchdog_recover(self, now: float) -> None: ...
    def warning_throttled(
        self,
        key: str,
        interval_seconds: float,
        message: str,
        *args: object,
        **kwargs: object,
    ) -> None: ...
    def write_auto_audit_event(self, reason: str, cached: bool = False) -> None: ...
    def mark_failure(self, key: str) -> None: ...
    def mark_recovery(self, key: str, message: str, *args: object) -> None: ...
    def source_retry_ready(self, key: str, now: float | None = None) -> bool: ...
    def source_retry_remaining(self, key: str, now: float | None = None) -> int: ...
    def delay_source_retry(
        self,
        key: str,
        now: float | None = None,
        delay_seconds: float | None = None,
    ) -> None: ...


class ShellyControllerPort(Protocol):
    def request(self, url: str) -> JsonObject: ...
    def request_with_session(self, session: ShellyHttpSession, url: str) -> JsonObject: ...
    def rpc_call(self, method: str, **params: ShellyRpcScalar) -> JsonObject: ...
    def rpc_call_with_session(
        self,
        session: ShellyHttpSession,
        method: str,
        **params: ShellyRpcScalar,
    ) -> JsonObject: ...
    def worker_fetch_pm_status(self) -> JsonObject: ...
    def build_local_pm_status(self, relay_on: bool) -> ShellyPmStatus: ...
    def publish_local_pm_status(self, relay_on: bool, now: float | None = None) -> ShellyPmStatus: ...
    def queue_relay_command(self, relay_on: bool, now: float | None = None) -> None: ...
    def peek_pending_relay_command(self) -> PendingRelayCommand: ...
    def clear_pending_relay_command(self, relay_on: bool) -> None: ...
    def worker_apply_pending_relay_command(self) -> None: ...
    def start_io_worker(self) -> None: ...
    def fetch_pm_status(self) -> JsonObject: ...
    def set_relay(self, on: bool) -> JsonObject: ...
    def phase_selection_requires_pause(self) -> bool: ...
    def set_phase_selection(self, selection: object) -> str: ...


class PublishControllerPort(Protocol):
    def ensure_state(self) -> None: ...
    def publish_field(
        self,
        field: str,
        value: object,
        now: float | None = None,
        interval_seconds: float | None = None,
        force: bool = False,
    ) -> bool: ...
    def last_accepted_field(self, field: str) -> object: ...
    def publish_live_measurements(
        self,
        power: float,
        voltage: float,
        total_current: float,
        phase_data: PhaseData,
        now: float | None,
    ) -> bool: ...
    def publish_energy_time_measurements(
        self,
        energy_forward: float,
        phase_energies: Mapping[str, float],
        charging_time: int,
        session_energy: float,
        now: float | None,
    ) -> bool: ...
    def publish_config_paths(self, startstop_display: int, now: float | None) -> bool: ...
    def publish_diagnostic_paths(self, now: float) -> bool: ...


class StateControllerPort(Protocol):
    def state_summary(self) -> str: ...
    def current_runtime_state(self) -> dict[str, object]: ...
    def load_runtime_state(self) -> None: ...
    def save_runtime_state(self) -> None: ...
    def save_runtime_overrides(self) -> None: ...
    def flush_runtime_overrides(self, now: float | None = None) -> None: ...
    def validate_runtime_config(self) -> None: ...
    def load_config(self) -> configparser.ConfigParser: ...


class CompanionControllerPort(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def publish(self, now: float | None = None) -> bool: ...


class UpdateControllerPort(Protocol):
    def update(self) -> bool: ...
    def sign_of_life(self) -> bool: ...


class BootstrapControllerPort(Protocol):
    def initialize_service(self) -> None: ...
