#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Main-loop contract for DBus adapter process mixins."""

from __future__ import annotations

from typing import Any, Protocol

from venus_evcharger.dbus_adapter_components import DbusCircuitBreaker, ResourceMonitor, TickHealth
from venus_evcharger.dbus_adapter_read import DbusReadExecutor
from venus_evcharger.dbus_adapter_write import DbusWriteScheduler
from venus_evcharger.dbus_gateway import DbusCacheStore, GatewayPaths


class DbusAdapterLoopContext(Protocol):  # pragma: no cover
    """Main-loop scheduling surface required by ``DbusAdapterLoopMixin``."""

    paths: GatewayPaths
    cache: DbusCacheStore
    circuit: DbusCircuitBreaker
    resource_monitor: ResourceMonitor
    tick_health: TickHealth
    read_executor: DbusReadExecutor
    write_scheduler: DbusWriteScheduler
    tick_seconds: float
    min_tick_seconds: float
    max_tick_seconds: float
    slo_mainloop_gap_max_ms: float
    slo_core_read_max_age_seconds: float
    _main_loop: Any
    _stop: bool
    _next_work_tick_monotonic: float
    _last_resource_snapshot: dict[str, Any]
    _last_tick_at: float
    _last_tick_monotonic: float
    _last_tick_duration_ms: float
    _prefer_read_next: bool

    def _install_signal_handlers(self) -> None: ...
    def _tick(self) -> bool: ...
    def start_socket(self) -> None: ...
    def close_socket(self) -> None: ...
    def process_socket_once(self) -> None: ...
    def ensure_dbus_service(self) -> None: ...
    def process_introspection_requests_once(self) -> None: ...
    def publish_cache(self) -> None: ...
    def update_adaptive_tick(self) -> None: ...
    def apply_slo_regulation(self) -> None: ...
    def adaptive_tick_seconds(self, *, circuit_state: str, resource_state: str) -> float: ...
    def process_one_dbus_operation_once(self) -> bool: ...
    def _refresh_initial_services_once(self) -> bool: ...
    def _priority_read_performed(self) -> bool: ...
    def _process_standard_operation_once(self) -> bool: ...
    def _reads_need_priority(self) -> bool: ...
    def _core_reads_stale(self) -> bool: ...
    def _core_read_age(self, key: str, now: float) -> float: ...
    def refresh_services_if_due_once(self) -> bool: ...
    def enqueue_background_introspection_if_due(self) -> None: ...
    def _process_preferred_read_or_write(self) -> bool: ...
    def _try_read_then_write(self) -> bool: ...
    def _try_write_then_read(self) -> bool: ...
    def _try_scheduled_write(self, *, prefer_read_next: bool) -> bool: ...
    def poll_one_due_read_once(self) -> bool: ...
