from typing import Any

class SystemBus:
    def __init__(self, private: bool = False) -> None: ...
    def get_object(self, bus_name: str, object_path: str) -> object: ...

def Interface(obj: object, dbus_interface: str | None = None) -> Any: ...
