# SPDX-License-Identifier: GPL-3.0-or-later
"""Focused mutmut test selections for optional mutation audits."""

from __future__ import annotations


_UPDATE_RUNTIME_TESTS = (
    'tests/test_venus_evcharger_update_cycle_controller.py',
    'tests/test_update_edge_contracts.py',
)
_UPDATE_TIME_SAFETY_TESTS = ('tests/test_update_time_safety_contracts.py',)
_UPDATE_INPUT_VALIDATION_TESTS = ('tests/test_update_input_validation_contracts.py',)
_PHASE_SWITCH_PERSISTENCE_TESTS = ('tests/test_phase_switch_persistence_contracts.py',)


FOCUSED_TEST_SELECTIONS_CORE: tuple[tuple[str, tuple[str, ...]], ...] = (('venus_evcharger/app/', ('tests/test_app_bootstrap_support.py',)),
 ('scripts/dev/', ('tests/test_mutation_audit_script.py',)),
 ('venus_evcharger_auto_input_helper.py', ('tests/test_venus_evcharger_auto_input_helper.py',)),
 ('venus_evcharger/energy/grid_fusion', ('tests/test_grid_measurement_fusion.py',)),
 ('venus_evcharger/inputs/helper/grid_fusion_snapshot.py', ('tests/test_grid_measurement_fusion.py',)),
 ('venus_evcharger/backend/modbus_transport_serial.py', ('tests/test_venus_evcharger_backend_modbus_transport.py',)),
 ('venus_evcharger/backend/shelly_io_worker_status.py', ('tests/test_venus_evcharger_backend_shelly_support.py',)),
 ('venus_evcharger/bootstrap/wizard_energy_bundle.py', ('tests/test_bootstrap_wizard_energy_contracts.py',)),
 ('venus_evcharger/control/http_api.py', ('tests/test_control_http_lifecycle_contracts.py',)),
 ('venus_evcharger/control/http_api_events.py', ('tests/test_control_http_events_contracts.py',)),
 ('venus_evcharger/control/service.py', ('tests/test_control_service_contracts.py',)),
 ('venus_evcharger/controllers/auto.py', ('tests/test_auto_controller_facade_contracts.py',)),
 ('venus_evcharger/controllers/state.py', ('tests/test_state_controller_config_contracts.py',)),
 ('venus_evcharger/controllers/state_config.py', ('tests/test_state_controller_config_contracts.py',)),
 ('venus_evcharger/controllers/state_json.py', ('tests/test_state_json_contracts.py',)),
 ('venus_evcharger/controllers/state_persistence.py', ('tests/test_state_persistence_contracts.py',)),
 ('venus_evcharger/controllers/state_restore.py', ('tests/test_venus_evcharger_state_controller.py', 'tests/test_state_restore_contracts.py')),
 ('venus_evcharger/controllers/state_restore_victron_ess.py', ('tests/test_state_restore_victron_ess_contracts.py',)),
 ('venus_evcharger/controllers/state_runtime_normalize.py', ('tests/test_state_runtime_normalize_contracts.py',)),
 ('venus_evcharger/controllers/state_runtime_overrides.py', ('tests/test_state_runtime_overrides_contracts.py',)),
 ('venus_evcharger/controllers/state_runtime_snapshot.py',
  ('tests/test_state_runtime_snapshot_contracts.py',
   'tests/test_state_runtime_snapshot_defaults_contracts.py',
   'tests/venus_evcharger_state_controller_cases_primary.py',
   'tests/venus_evcharger_state_controller_cases_quaternary.py')),
 ('venus_evcharger/controllers/state_runtime_snapshot_victron.py',
  ('tests/test_state_runtime_snapshot_contracts.py',
   'tests/test_state_runtime_snapshot_defaults_contracts.py',
   'tests/test_branch_coverage_next_cluster_two.py')),
 ('venus_evcharger/controllers/state_specs.py', ('tests/test_state_runtime_overrides_contracts.py',)),
 ('venus_evcharger/controllers/state_summary.py',
  ('tests/test_state_summary_contracts.py',
   'tests/test_state_summary_edge_contracts.py',
   'tests/venus_evcharger_state_controller_cases_primary.py',
   'tests/venus_evcharger_state_controller_cases_quaternary.py')),
 ('venus_evcharger/controllers/state_validation.py',
  ('tests/test_state_validation_contracts.py',
   'tests/test_state_validation_logging_contracts.py',
   'tests/venus_evcharger_state_controller_cases_tertiary.py')),
 ('venus_evcharger/controllers/write.py',
  ('tests/test_write_controller_contracts.py',
   'tests/test_write_controller_handler_contracts.py',
   'tests/test_venus_evcharger_write_controller.py')),
 ('venus_evcharger/controllers/write_snapshot.py',
  ('tests/test_write_snapshot_contracts.py',
   'tests/test_venus_evcharger_write_controller.py',
   'tests/test_remaining_coverage_helpers.py')),
 ('venus_evcharger/controllers/write_support.py',
  ('tests/test_write_support_contracts.py',
   'tests/test_write_controller_handler_contracts.py',
   'tests/test_venus_evcharger_write_controller.py')),
 ('venus_evcharger/auto/logic_samples.py', ('tests/test_auto_backend_bootstrap_edge_contracts.py',)),
 ('venus_evcharger/core/common.py',
  ('tests/test_core_common_boundary_contracts.py',
   'tests/test_venus_evcharger_common.py')),
 ('venus_evcharger/core/common_auto.py',
  ('tests/test_core_common_auto_contracts.py', 'tests/test_venus_evcharger_common.py')),
 ('venus_evcharger/core/common_schedule.py',
  ('tests/test_core_common_schedule_contracts.py', 'tests/test_venus_evcharger_common.py')),
 ('venus_evcharger/core/common_types.py',
  ('tests/test_core_common_types_contracts.py', 'tests/test_venus_evcharger_common.py')),
 ('venus_evcharger/core/common_values.py',
  ('tests/test_core_common_values_contracts.py', 'tests/test_venus_evcharger_common.py')),
 ('venus_evcharger/core/contracts_basic.py',
  ('tests/test_core_contracts_basic_contracts.py', 'tests/test_venus_evcharger_common.py')),
 ('venus_evcharger/core/contracts_bootstrap.py',
  ('tests/test_core_contracts_bootstrap_contracts.py', 'tests/test_bootstrap_contracts.py')),
 ('venus_evcharger/core/contracts_control.py',
  ('tests/test_core_contracts_control_command_contracts.py',
   'tests/test_core_contracts_control_api_contracts.py',
   'tests/test_venus_evcharger_control_contracts.py')),
 ('venus_evcharger/core/contracts_outward.py',
  ('tests/test_core_contracts_outward_contracts.py', 'tests/test_venus_evcharger_common.py')),
 ('venus_evcharger/core/contracts_snapshot.py',
  ('tests/test_core_contracts_snapshot_contracts.py', 'tests/test_venus_evcharger_common.py')),
 ('venus_evcharger/core/contracts_state_endpoints.py',
  ('tests/test_core_contracts_state_endpoints_contracts.py', 'tests/test_venus_evcharger_state_contracts.py')),
 ('venus_evcharger/core/contracts_state_operational.py', ('tests/test_venus_evcharger_state_contracts.py',)),
 ('venus_evcharger/core/contracts_state_shared.py',
  ('tests/test_core_contracts_state_shared_contracts.py',
   'tests/test_core_contracts_state_endpoints_contracts.py',
   'tests/test_venus_evcharger_state_contracts.py')),
 ('venus_evcharger/core/return_contracts.py',
  ('tests/test_core_return_contracts.py',)),
 ('venus_evcharger/core/shared.py',
  ('tests/test_core_shared_contracts.py', 'tests/test_venus_evcharger_shared.py')),
 ('venus_evcharger/ipc/command_mailbox.py',
  ('tests/test_ipc_command_mailbox_contracts.py',
   'tests/test_publication_mailbox_contracts.py',
   'tests/test_fast_publication_ipc.py')),
 ('venus_evcharger/ipc/core_commands.py',
  ('tests/test_ipc_command_mailbox_contracts.py',)),
 ('venus_evcharger/ipc/energy_binary.py',
  ('tests/test_energy_binary_ipc_contracts.py',)),
 ('venus_evcharger/ipc/energy_refresh.py',
  ('tests/test_energy_ipc_contracts.py',)),
 ('venus_evcharger/ipc/energy_snapshots.py',
  ('tests/test_energy_ipc_contracts.py',)),
 ('venus_evcharger/ipc/energy_types.py',
  ('tests/test_energy_ipc_contracts.py',)),
 ('venus_evcharger/ipc/energy_validation.py',
  ('tests/test_energy_ipc_contracts.py',)),
 ('venus_evcharger/ipc/energy_values.py',
  ('tests/test_energy_ipc_contracts.py',)),
 ('venus_evcharger/ipc/gateway_diagnostics.py',
  ('tests/test_gateway_diagnostics_contracts.py',)),
 ('venus_evcharger/ipc/gateway_operations.py',
  ('tests/test_gateway_semantic_operations.py',)),
 ('venus_evcharger/ipc/gateway_pressure.py',
  ('tests/test_gateway_pressure_contracts.py',)),
 ('venus_evcharger/ipc/gateway_publication.py',
  ('tests/test_gateway_publication_contracts.py',)),
 ('venus_evcharger/dbus_gateway_commands.py',
  ('tests/test_dbus_gateway_primitives.py',
   'tests/test_publication_mailbox_contracts.py',
   'tests/test_fast_publication_scheduler_contracts.py',
   'tests/test_ipc_publication_edges.py')),
 ('venus_evcharger/dbus_adapter/rate.py', ('tests/test_dbus_gateway_adapter_scheduler.py',)),
 ('venus_evcharger/dbus_adapter/resources.py',
  ('tests/test_dbus_adapter_resource_contracts.py',)),
 ('venus_evcharger/dbus_gateway_cache.py',
  ('tests/test_dbus_gateway_primitives.py',
   'tests/test_dbus_adapter_freshness_contracts.py',
   'tests/test_energy_binary_ipc_contracts.py')),
 ('venus_evcharger/dbus_gateway_client.py',
  ('tests/test_dbus_gateway_primitives.py',
   'tests/test_energy_binary_ipc_contracts.py',
   'tests/test_gateway_boundary_edge_contracts.py',
   'tests/test_gateway_semantic_operations.py',
   'tests/test_disable_generic_shelly_once_contracts.py')),
 ('venus_evcharger/dbus_gateway_core.py',
  ('tests/test_dbus_gateway_primitives.py',
   'tests/test_energy_binary_ipc_contracts.py',
   'tests/test_gateway_boundary_edge_contracts.py')),
 ('venus_evcharger/dbus_adapter/read/pv.py',
  ('tests/test_dbus_adapter_read_pv_contracts.py',
   'tests/test_dbus_adapter_discovery_mutation_contracts.py')),
 ('venus_evcharger/dbus_adapter/refresh_state.py',
  ('tests/test_dbus_adapter_refresh_state_contracts.py',)),
 ('venus_evcharger/dbus_adapter/read/executor.py',
  ('tests/test_dbus_gateway_adapter_scheduler.py',)),
 ('venus_evcharger/dbus_adapter/scheduling.py', ('tests/test_dbus_adapter_scheduler_contracts.py',)),
 ('venus_evcharger/dbus_adapter/health/backpressure.py', ('tests/test_dbus_adapter_backpressure_contracts.py',)),
 ('venus_evcharger/dbus_adapter/health/freshness.py', ('tests/test_dbus_adapter_freshness_contracts.py',)),
 ('venus_evcharger/dbus_adapter/health/history.py', ('tests/test_dbus_adapter_health_history_contracts.py',)),
 ('venus_evcharger/dbus_adapter/health/queue.py', ('tests/test_dbus_adapter_health_queue_contracts.py',)),
 ('venus_evcharger/dbus_adapter/health/slo.py', ('tests/test_dbus_adapter_health_slo_contracts.py',)),
 ('venus_evcharger/dbus_adapter/jsonl.py', ('tests/test_dbus_adapter_jsonl_contracts.py',)),
 ('venus_evcharger/dbus_adapter/process/adapter.py', ('tests/test_dbus_adapter_process_contracts.py',)),
 ('venus_evcharger/dbus_adapter/process/config.py', ('tests/test_dbus_adapter_process_config_contracts.py',)),
 ('venus_evcharger/dbus_adapter/process/introspection.py',
  ('tests/test_energy_ipc_contracts.py',
   'tests/test_gateway_energy_snapshot_contracts.py',
   'tests/test_dbus_gateway_adapter_scheduler.py::DbusGatewayAdapterSchedulerTests::test_background_introspection_uses_discovery_targets_and_opaque_topology',
   'tests/test_dbus_gateway_adapter_scheduler.py::DbusGatewayAdapterSchedulerTests::test_gateway_non_write_introspection_command_contracts',
   'tests/test_dbus_gateway_adapter_scheduler.py::DbusGatewayAdapterSchedulerTests::test_non_write_introspection_timed_logging_main_and_json_ready',
  )),
 ('venus_evcharger/dbus_adapter/process/loop.py',
  ('tests/test_dbus_gateway_adapter_scheduler.py',)),
 ('venus_evcharger/dbus_adapter/process/introspection_snapshot.py',
  ('tests/test_dbus_adapter_introspection_snapshot_contracts.py',)),
 ('venus_evcharger/dbus_adapter/process/io.py', (
     'tests/test_dbus_gateway_adapter_scheduler.py::DbusGatewayAdapterSchedulerTests::test_poll_and_discovery_contracts',
     'tests/test_dbus_gateway_adapter_scheduler.py::DbusGatewayAdapterSchedulerTests::test_poll_and_discovery_edges',
     'tests/test_dbus_gateway_adapter_scheduler.py::DbusGatewayAdapterSchedulerTests::test_cache_publish_interval_contracts',
     'tests/test_dbus_gateway_adapter_scheduler.py::DbusGatewayAdapterSchedulerTests::test_signal_handlers_andlist_services_edges',
     'tests/test_dbus_gateway_adapter_scheduler.py::DbusGatewayAdapterSchedulerTests::test_timed_operation_contracts_record_latency_and_errors',
)),
 ('venus_evcharger/dbus_adapter/process/runtime.py', (
     'tests/test_dbus_gateway_adapter_scheduler.py::DbusGatewayAdapterSchedulerTests::test_signal_handlers_andlist_services_edges',
 )),
 ('venus_evcharger/dbus_adapter/process/socket.py', (
     'tests/test_dbus_adapter_process_ipc_contracts.py',
 )),
 ('venus_evcharger/dbus_adapter/read/aggregate.py', ('tests/test_dbus_adapter_read_aggregate_contracts.py',)),
 ('venus_evcharger/dbus_adapter/read/discovery.py',
  (
      'tests/test_gateway_energy_snapshot_contracts.py',
      'tests/test_dbus_adapter_discovery_mutation_contracts.py',
  )),
 ('venus_evcharger/dbus_adapter/read/keys.py',
  ('tests/test_gateway_energy_snapshot_contracts.py',)),
 ('venus_evcharger/dbus_adapter/read/semantic.py',
  ('tests/test_gateway_energy_snapshot_contracts.py',)),
 ('venus_evcharger/dbus_adapter/read/targets.py',
  ('tests/test_dbus_adapter_read_targets_contracts.py',)),
 ('venus_evcharger/dbus_adapter/read/spec.py', (
     'tests/test_dbus_gateway_adapter_scheduler.py::DbusGatewayAdapterSchedulerTests::test_read_spec_from_mapping_validates_known_fields',
 )),
 ('venus_evcharger/dbus_adapter/write/scheduler.py',
  ('tests/test_dbus_gateway_adapter_scheduler.py',)),
 ('venus_evcharger/dbus_adapter/write/health.py', ('tests/test_dbus_gateway_adapter_scheduler.py',)),
 ('venus_evcharger/dbus_adapter/write/publish.py', (
     'tests/test_dbus_gateway_adapter_scheduler.py',
     'tests/test_dbus_adapter_write_publish_mutation_contracts.py',
 )),
 ('venus_evcharger/dbus_adapter/write/semantic.py',
  ('tests/test_dbus_adapter_write_semantic_mutation_contracts.py',)),
 ('venus_evcharger/dbus_adapter/write/core.py',
  ('tests/test_dbus_gateway_adapter_scheduler.py',)),
 ('venus_evcharger/dbus_adapter/write/support.py',
  ('tests/test_dbus_gateway_adapter_scheduler.py',)),
 ('venus_evcharger/dbus_gateway_surface.py', ('tests/test_dbus_gateway_primitives.py',)),
 ('venus_evcharger/publish/gateway_diagnostics.py',
  ('tests/test_publish_gateway_diagnostics_contracts.py',)),
 ('venus_evcharger/energy/config.py', (
     'tests/test_energy_config_contracts.py',
 )),
 ('venus_evcharger/energy/connectors.py', ('tests/test_energy_connectors_facade_contracts.py',)),
 ('venus_evcharger/energy/connectors_command.py', ('tests/test_energy_connectors_command_contracts.py',)),
 ('venus_evcharger/energy/connectors_common.py', ('tests/test_energy_connectors_common_contracts.py',)),
 ('venus_evcharger/energy/connectors_modbus.py', ('tests/test_energy_connectors_modbus_contracts.py',)),
 ('venus_evcharger/energy/connectors_opendtu.py', ('tests/test_energy_connectors_opendtu_contracts.py',)),
 ('venus_evcharger/energy/connectors_template.py', ('tests/test_energy_connectors_template_contracts.py',)),
 ('venus_evcharger/energy/learning.py', ('tests/test_venus_evcharger_energy_aggregate.py',)),
 ('venus_evcharger/energy/learning_coercion.py', ('tests/test_energy_learning_coercion_contracts.py',)),
 ('venus_evcharger/energy/probe.py', (
     'tests/test_energy_probe_facade_contracts.py',
     'tests/test_venus_evcharger_energy_probe.py',
 )),
 ('venus_evcharger/energy/probe_cli.py', ('tests/test_energy_probe_cli_contracts.py',)),
 ('venus_evcharger/energy/probe_core.py', ('tests/test_energy_probe_core_contracts.py',)),
 ('venus_evcharger/energy/probe_huawei.py', ('tests/test_energy_probe_huawei_contracts.py',)),
 ('venus_evcharger/energy/profiles.py', ('tests/test_energy_profiles_contracts.py',)),
 ('venus_evcharger/energy/recommendation_schema.py', ('tests/test_energy_recommendation_schema_contracts.py',)),
 ('venus_evcharger/inputs/helper/capacity_persistence.py', ('tests/test_auto_input_capacity_persistence.py',)),
 ('venus_evcharger/inputs/helper/config_runtime.py',
  ('tests/test_auto_input_helper_config_contracts.py', 'tests/test_venus_evcharger_auto_input_helper.py')),
 ('venus_evcharger/inputs/helper/glib_runtime.py', ('tests/test_auto_input_helper_glib_runtime_contracts.py',)),
 ('venus_evcharger/inputs/helper/liveness.py',
  ('tests/test_auto_input_helper_snapshot_liveness_contracts.py', 'tests/test_venus_evcharger_auto_input_helper.py')),
 ('venus_evcharger/inputs/helper/snapshot.py', ('tests/test_auto_input_helper_snapshot_liveness_contracts.py',)),
 ('venus_evcharger/inputs/helper/sources.py',
  ('tests/test_auto_input_helper_sources_contracts.py', 'tests/test_auto_input_helper_snapshot_liveness_contracts.py')),
 ('venus_evcharger/inputs/helper/energy_gateway.py',
  ('tests/test_auto_input_helper_gateway_contracts.py',
   'tests/test_auto_input_helper_refresh_contracts.py')),
 ('venus_evcharger/inputs/supervisor.py',
  ('tests/test_venus_evcharger_auto_input_supervisor.py',)),
 ('venus_evcharger/inputs/supervisor_process.py',
  ('tests/test_auto_input_supervisor_process_contracts.py',
   'tests/test_venus_evcharger_auto_input_supervisor.py')),
 ('venus_evcharger/inputs/supervisor_snapshot_runtime.py',
  ('tests/test_auto_input_supervisor_snapshot_runtime_contracts.py',
   'tests/test_venus_evcharger_auto_input_supervisor.py')),
 ('venus_evcharger/inputs/supervisor_snapshot_validation.py',
  ('tests/test_auto_input_supervisor_snapshot_validation_contracts.py',)),
 ('venus_evcharger/inputs/supervisor_snapshot_values.py',
  ('tests/test_auto_input_supervisor_snapshot_validation_contracts.py',)),
 ('venus_evcharger/inventory/config.py',
  ('tests/test_device_inventory_config.py', 'tests/test_inventory_config_contracts.py')),
 ('venus_evcharger/inventory/render.py', ('tests/test_device_inventory_config.py',)),
 ('venus_evcharger/inventory/schema.py', ('tests/test_device_inventory_config.py',)),
 ('venus_evcharger/ops/disable_generic_shelly_once.py',
  ('tests/test_disable_generic_shelly_once_contracts.py',)),
 ('venus_evcharger/ops/forensic_observer.py', ('tests/test_forensic_observer_contracts.py',)),
 ('venus_evcharger/ports/auto.py',
  ('tests/test_venus_evcharger_ports.py', 'tests/test_ports_auto_contracts.py')),
 ('venus_evcharger/ports/gateway_diagnostics.py',
  ('tests/test_gateway_diagnostics_contracts.py',)),
 ('venus_evcharger/ports/gateway_diagnostic_values.py',
  ('tests/test_gateway_diagnostics_contracts.py',)),
 ('venus_evcharger/ports/gateway_diagnostics_validation.py',
  ('tests/test_gateway_diagnostics_contracts.py',)),
 ('venus_evcharger/ports/gateway_operations.py',
  ('tests/test_gateway_semantic_operations.py',)),
 ('venus_evcharger/ports/gateway_pressure.py',
  ('tests/test_gateway_pressure_contracts.py',)),
 ('venus_evcharger/ports/gateway_publication.py',
  ('tests/test_gateway_publication_contracts.py',)),
 ('venus_evcharger/ports/write.py',
  ('tests/test_ports_write_contracts.py',
   'tests/test_venus_evcharger_ports.py',
   'tests/test_boundary_port_edge_contracts.py')),
 ('venus_evcharger/ports/write_runtime.py',
  ('tests/test_venus_evcharger_ports.py', 'tests/test_boundary_port_edge_contracts.py')),
 ('venus_evcharger/publish/dbus_diagnostics_sources.py',
  ('tests/test_venus_evcharger_publisher_controller.py', 'tests/test_boundary_port_edge_contracts.py')),
 ('venus_evcharger/publish/dbus_config.py', ('tests/test_venus_evcharger_publisher_controller.py',)),
 ('venus_evcharger/runtime/async_mainloop_executor.py',
  ('tests/test_venus_evcharger_runtime_support_controller.py',)),
 ('venus_evcharger/runtime/async_control_types.py',
  ('tests/test_runtime_async_control_types.py',)),
 ('venus_evcharger/runtime/async_mainloop_control.py',
  ('tests/test_runtime_async_mainloop_control_contracts.py',
   'tests/test_venus_evcharger_runtime_support_controller.py')),
 ('venus_evcharger/runtime/async_mainloop_state.py',
  ('tests/test_runtime_async_mainloop_state_contracts.py',
   'tests/test_venus_evcharger_runtime_support_controller.py')),
 ('venus_evcharger/runtime/async_mainloop_watchdog.py',
  ('tests/test_runtime_async_mainloop_watchdog_contracts.py',)),
 ('venus_evcharger/runtime/audit.py',
  ('tests/test_runtime_audit_contracts.py',
   'tests/test_venus_evcharger_runtime_support_controller.py')),
 ('venus_evcharger/runtime/audit_fields.py',
  ('tests/test_runtime_audit_fields_contracts.py',)),
 ('venus_evcharger/runtime/health.py',
  ('tests/test_runtime_health_contracts.py',)),
 ('venus_evcharger/runtime/output_path.py',
  ('tests/test_runtime_output_path_contracts.py',
   'tests/test_dbus_adapter_jsonl_contracts.py',
   'tests/test_dbus_adapter_process_config_contracts.py')),
 ('venus_evcharger/runtime/setup.py',
  ('tests/test_runtime_setup_contracts.py',)),
 ('venus_evcharger/runtime/setup_support.py',
  ('tests/test_runtime_setup_support_contracts.py',)),
 ('venus_evcharger/runtime/software_update_setup.py',
  ('tests/test_runtime_software_update_setup.py',)),
 ('venus_evcharger/runtime/support.py',
  ('tests/test_runtime_support_contracts.py',)),
 ('venus_evcharger/service/control_state_core.py',
  ('tests/test_control_service_contracts.py',
   'tests/test_venus_evcharger_control_api.py',
   'tests/test_service_control_state_contracts.py')),
 ('venus_evcharger/service/control_runtime.py',
  ('tests/test_service_control_runtime_contracts.py', 'tests/test_service_control_state_contracts.py')),
 ('venus_evcharger/service/control.py', ('tests/test_service_control_state_contracts.py',)),
 ('venus_evcharger/service/control_state_config.py', ('tests/test_service_control_state_contracts.py',)),
 ('venus_evcharger/service/control_state_meta.py', ('tests/test_service_control_state_contracts.py',)),
 ('venus_evcharger/service/control_state_operational.py',
  ('tests/test_service_operational_state_contracts.py',)),
 ('venus_evcharger/service/control_state_operational_support.py',
  ('tests/test_service_operational_state_contracts.py',)),
 ('venus_evcharger/service/control_state_victron.py', ('tests/test_service_operational_state_contracts.py',)),
 ('venus_evcharger/service/composition_guards.py',
  ('tests/test_service_composition_contracts.py',
   'tests/test_boundary_port_edge_contracts.py')),
 ('venus_evcharger/update/offline_publish.py',
  (*_UPDATE_RUNTIME_TESTS,
   'tests/test_venus_evcharger_branch_misc.py',
   *_UPDATE_INPUT_VALIDATION_TESTS)),
 ('venus_evcharger/update/pm_snapshot.py',
  (*_UPDATE_RUNTIME_TESTS,
   'tests/test_remaining_coverage_helpers.py',
   *_UPDATE_TIME_SAFETY_TESTS)),
 ('venus_evcharger/update/readback_resolver.py', _UPDATE_RUNTIME_TESTS),
 ('venus_evcharger/update/relay_charger_current.py', _UPDATE_RUNTIME_TESTS),
 ('venus_evcharger/update/relay_charger_current_targets.py',
  (*_UPDATE_RUNTIME_TESTS, *_UPDATE_TIME_SAFETY_TESTS)),
 ('venus_evcharger/update/relay_charger_health.py', _UPDATE_RUNTIME_TESTS),
 ('venus_evcharger/update/controller.py', ('tests/test_update_controller_transport_contracts.py',)),
 ('venus_evcharger/update/relay_charger_transport.py',
  ('tests/test_update_controller_transport_contracts.py', *_UPDATE_RUNTIME_TESTS)),
 ('venus_evcharger/update/relay_phase_decision.py',
  (*_UPDATE_RUNTIME_TESTS, *_UPDATE_INPUT_VALIDATION_TESTS)),
 ('venus_evcharger/update/relay_phase_publish.py', _UPDATE_RUNTIME_TESTS),
 ('venus_evcharger/update/relay_phase_switch_policy.py',
  (*_UPDATE_RUNTIME_TESTS, *_PHASE_SWITCH_PERSISTENCE_TESTS)),
 ('venus_evcharger/update/relay_status_publish.py', _UPDATE_RUNTIME_TESTS),
 ('venus_evcharger/update/state.py',
  (*_UPDATE_RUNTIME_TESTS,
   'tests/test_backend_readback_snapshot_contracts.py',
   *_UPDATE_TIME_SAFETY_TESTS)),
 ('venus_evcharger/update/victron_ess_balance_apply_pid.py',
  ('tests/test_victron_ess_balance_apply_pid_contracts.py',)),
 ('venus_evcharger/update/victron_ess_balance_apply_sources.py',
  ('tests/test_victron_ess_balance_apply_sources_contracts.py',)),
 ('venus_evcharger/update/victron_ess_balance_apply_write.py',
  ('tests/test_victron_ess_balance_apply_write_contracts.py',)),
 ('venus_evcharger/update/victron_ess_balance_recommendation_support.py',
  ('tests/test_victron_ess_balance_recommendation_support_contracts.py',)),
 ('venus_evcharger/update/victron_ess_balance_recommendation.py',
  ('tests/test_victron_ess_balance_recommendation_contracts.py',)),
 ('venus_evcharger/update/victron_ess_balance_learning_profiles_support.py',
  ('tests/test_victron_ess_balance_learning_profiles_support_contracts.py',
   'tests/test_branch_coverage_hotspots.py')),
 ('venus_evcharger/update/victron_ess_balance_learning_profiles.py',
  ('tests/test_victron_ess_balance_learning_profiles_contracts.py',
   'tests/test_victron_ess_balance_learning_profiles_support_contracts.py')),
 ('venus_evcharger/update/victron_ess_balance_learning_telemetry.py',
  ('tests/test_victron_ess_balance_learning_telemetry.py',
   'tests/test_victron_ess_balance_learning_telemetry_contracts.py',
   'tests/test_victron_ess_balance_learning_profiles_contracts.py')),
 ('venus_evcharger/update/victron_ess_balance_adaptive.py',
  ('tests/test_victron_ess_balance_adaptive_contracts.py',
   'tests/test_venus_evcharger_update_cycle_controller.py',
   'tests/test_branch_coverage_hotspots.py')),
 ('venus_evcharger/update/victron_ess_balance_apply.py',
  ('tests/test_victron_ess_balance_apply_contracts.py',
   'tests/test_victron_ess_balance_apply_restore_contracts.py',
   'tests/test_venus_evcharger_update_cycle_controller.py',
   'tests/test_branch_coverage_hotspots.py')),
 ('venus_evcharger/update/victron_ess_balance_safety_support.py',
  ('tests/test_victron_ess_balance_safety_contracts.py',
   'tests/test_victron_ess_balance_safety_threshold_contracts.py',
   'tests/test_victron_ess_balance_safety_support_contracts.py',
   'tests/test_branch_coverage_hotspots.py',
   'tests/test_victron_ess_balance_learning_telemetry.py')),
 ('venus_evcharger/update/victron_ess_balance_safety.py',
  ('tests/test_victron_ess_balance_safety_contracts.py',
   'tests/test_victron_ess_balance_safety_threshold_contracts.py',
   'tests/test_victron_ess_balance_safety_support_contracts.py',
   'tests/test_branch_coverage_hotspots.py',
   'tests/test_victron_ess_balance_learning_telemetry.py')),
 ('venus_evcharger/update/',
  ('tests/test_venus_evcharger_update_cycle_controller.py',
   'tests/test_branch_coverage_hotspots.py',
   'tests/test_victron_ess_balance_learning_telemetry.py')),
 ('venus_evcharger/controllers/state_', ('tests/test_venus_evcharger_state_controller.py',)),
 ('venus_evcharger/topology/', ('tests/test_topology_config.py',)),
 ('venus_evcharger/backend/template_meter.py',
  ('tests/test_venus_evcharger_backend_template_meter.py', 'tests/test_venus_evcharger_backend_template_support.py')),
 ('venus_evcharger/backend/template_switch.py',
  ('tests/test_venus_evcharger_backend_template_switch.py',
   'tests/test_venus_evcharger_backend_template_support.py',
   'tests/test_venus_evcharger_backend_tuya.py')),
 ('venus_evcharger/backend/template_charger.py',
  ('tests/test_venus_evcharger_backend_template_charger.py', 'tests/test_venus_evcharger_backend_template_support.py')),
 ('venus_evcharger/backend/template_support.py',
  ('tests/test_venus_evcharger_backend_template_support.py',
   'tests/test_venus_evcharger_backend_template_meter.py',
   'tests/test_venus_evcharger_backend_template_switch.py',
   'tests/test_venus_evcharger_backend_template_charger.py')),
 ('venus_evcharger/backend/shelly_support.py',
  ('tests/test_venus_evcharger_backend_shelly_support.py',
   'tests/test_venus_evcharger_backend_shelly_meter.py',
   'tests/test_venus_evcharger_backend_switch.py')),
 ('venus_evcharger/backend/shelly_io_runtime.py',
  ('tests/test_venus_evcharger_shelly_io_controller.py',
   'tests/test_venus_evcharger_backend_shelly_support.py',
   'tests/test_venus_evcharger_backend_shelly_meter.py')),
 ('venus_evcharger/backend/shelly_meter.py',
  ('tests/test_venus_evcharger_backend_shelly_meter.py', 'tests/test_venus_evcharger_backend_shelly_support.py')),
 ('venus_evcharger/backend/shelly_switch.py',
  ('tests/test_venus_evcharger_backend_switch.py', 'tests/test_venus_evcharger_backend_shelly_support.py')),
 ('venus_evcharger/backend/base.py', ('tests/test_backend_base_contracts.py',)),
 ('venus_evcharger/backend/cerbo_gx_relay_switch.py', ('tests/test_venus_evcharger_backend_cerbo_gx_relay_switch.py',)),
 ('venus_evcharger/backend/goe_charger.py',
  ('tests/test_venus_evcharger_backend_goe_charger.py',
   'tests/venus_evcharger_backend_factory_charger_cases.py',
   'tests/venus_evcharger_backend_probe_command_cases.py')),
 ('venus_evcharger/backend/modbus_charger.py',
  ('tests/test_venus_evcharger_backend_modbus_charger.py',
   'tests/test_venus_evcharger_backend_modbus_profiles.py',
   'tests/venus_evcharger_backend_factory_charger_cases.py')),
 ('venus_evcharger/backend/modbus_client.py', ('tests/test_venus_evcharger_backend_modbus_client.py',)),
 ('venus_evcharger/backend/modbus_profile_models.py',
  ('tests/test_venus_evcharger_backend_modbus_profiles.py', 'tests/test_venus_evcharger_backend_modbus_charger.py')),
 ('venus_evcharger/backend/modbus_profiles.py',
  ('tests/test_venus_evcharger_backend_modbus_profiles.py',
   'tests/test_venus_evcharger_backend_modbus_charger.py',
   'tests/venus_evcharger_backend_factory_charger_cases.py')),
 ('venus_evcharger/backend/modbus_transport.py', ('tests/test_venus_evcharger_backend_modbus_transport.py',)),
 ('venus_evcharger/backend/modbus_transport_config.py', ('tests/test_venus_evcharger_backend_modbus_transport.py',)),
 ('venus_evcharger/backend/models.py', ('tests/test_venus_evcharger_backend_models.py',)),
 ('venus_evcharger/backend/native_modbus_backend.py', ('tests/test_native_modbus_backend_contracts.py',)),
 ('venus_evcharger/backend/shelly_contactor_switch.py', ('tests/test_shelly_contactor_switch_contracts.py',)),
 ('venus_evcharger/backend/shelly_io.py', ('tests/test_venus_evcharger_shelly_io_controller.py',)),
 ('venus_evcharger/backend/shelly_io_capabilities.py', ('tests/test_venus_evcharger_shelly_io_controller.py',)),
 ('venus_evcharger/backend/shelly_io_ports.py', ('tests/test_venus_evcharger_shelly_io_controller.py',)),
 ('venus_evcharger/backend/shelly_io_requests.py', ('tests/test_venus_evcharger_shelly_io_controller.py',)),
 ('venus_evcharger/backend/shelly_io_runtime_cache.py', ('tests/test_venus_evcharger_shelly_io_controller.py',)),
 ('venus_evcharger/backend/shelly_io_split.py', ('tests/test_venus_evcharger_shelly_io_controller.py',)),
 ('venus_evcharger/backend/shelly_io_types.py', ('tests/test_venus_evcharger_backend_shelly_support.py',)),
 ('venus_evcharger/backend/shelly_io_worker.py',
  ('tests/test_venus_evcharger_shelly_io_controller.py', 'tests/test_venus_evcharger_backend_shelly_support.py')),
 ('venus_evcharger/backend/shelly_io_worker_lifecycle.py', ('tests/test_venus_evcharger_shelly_io_controller.py',)),
 ('venus_evcharger/backend/shelly_io_worker_transport.py', ('tests/test_venus_evcharger_shelly_io_controller.py',)),
 ('venus_evcharger/backend/shelly_profiles.py', ('tests/test_venus_evcharger_backend_shelly_support.py',)),
 ('venus_evcharger/backend/shelly_support_phase.py', ('tests/test_venus_evcharger_backend_shelly_support.py',)),
 ('venus_evcharger/backend/simpleevse_charger.py', ('tests/test_venus_evcharger_backend_simpleevse_charger.py',)),
 ('venus_evcharger/backend/smartevse_charger.py', ('tests/test_venus_evcharger_backend_smartevse_charger.py',)),
 ('venus_evcharger/backend/switch_group.py', ('tests/test_venus_evcharger_backend_switch.py',)),
 ('venus_evcharger/backend/tasmota_meter.py', ('tests/test_venus_evcharger_backend_tasmota.py',)),
 ('venus_evcharger/backend/tasmota_switch.py', ('tests/test_venus_evcharger_backend_tasmota.py',)),
 ('venus_evcharger/backend/template_charger_contract.py', ('tests/test_venus_evcharger_backend_template_charger.py',)))
