# SPDX-License-Identifier: GPL-3.0-or-later
"""Focused mutmut test selections for optional mutation audits."""

from __future__ import annotations

FOCUSED_TEST_SELECTIONS_TAIL: tuple[tuple[str, tuple[str, ...]], ...] = (('venus_evcharger/bootstrap/wizard_choices.py', ('tests/test_bootstrap_wizard_choices.py',)),
 ('venus_evcharger/bootstrap/wizard_cli.py',
  ('tests/test_venus_evcharger_setup_wizard.py',
   'tests/test_venus_evcharger_setup_wizard_extensions.py',
   'tests/test_venus_evcharger_setup_wizard_branch_runtime.py',
   'tests/test_branch_coverage_next_cluster_seven.py',
   'tests/test_bootstrap_wizard_cli_facade.py')),
 ('venus_evcharger/bootstrap/wizard_cli_prompts.py', ('tests/test_bootstrap_wizard_cli_prompts.py',)),
 ('venus_evcharger/bootstrap/wizard_cli_interactive.py',
  ('tests/test_venus_evcharger_setup_wizard.py',
   'tests/test_venus_evcharger_setup_wizard_extensions.py',
   'tests/test_venus_evcharger_setup_wizard_branch_runtime.py',
   'tests/test_bootstrap_wizard_cli_interactive_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_cli_imports.py', ('tests/test_bootstrap_wizard_cli_imports.py',)),
 ('venus_evcharger/bootstrap/wizard_cli_non_interactive.py',
  ('tests/test_venus_evcharger_setup_wizard.py',
   'tests/test_venus_evcharger_setup_wizard_extensions.py',
   'tests/test_venus_evcharger_setup_wizard_branch_runtime.py',
   'tests/test_branch_coverage_next_cluster_seven.py',
   'tests/test_bootstrap_wizard_cli_non_interactive_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_cli_output.py',
  ('tests/test_venus_evcharger_setup_wizard_branch_coverage.py',
   'tests/test_branch_coverage_next_cluster.py',
   'tests/test_bootstrap_wizard_cli_output_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_cli_output_next.py',
  ('tests/test_venus_evcharger_setup_wizard_branch_coverage.py',
   'tests/test_bootstrap_wizard_cli_output_next_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_cli_parser.py', ('tests/test_bootstrap_wizard_cli_parser.py',)),
 ('venus_evcharger/bootstrap/wizard_energy.py',
  ('tests/test_branch_coverage_hotspots.py',
   'tests/test_venus_evcharger_setup_wizard.py',
   'tests/test_bootstrap_wizard_energy_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_guidance.py',
  ('tests/test_venus_evcharger_setup_wizard_branch_coverage.py',
   'tests/test_venus_evcharger_setup_wizard_branch_runtime.py',
   'tests/test_bootstrap_wizard_guidance_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_import.py', ('tests/test_bootstrap_wizard_import_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_inventory.py', ('tests/test_bootstrap_wizard_inventory_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_inventory_cli.py', ('tests/test_bootstrap_wizard_inventory_cli_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_inventory_cli_actions.py',
  ('tests/test_bootstrap_wizard_inventory_cli_actions_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_inventory_cli_payload.py',
  ('tests/test_bootstrap_wizard_inventory_cli_payload_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_inventory_cli_guided_common.py',
  ('tests/test_bootstrap_wizard_inventory_cli_guided_common_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_inventory_cli_guided_profile_specs.py',
  ('tests/test_bootstrap_wizard_inventory_cli_guided_profile_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_inventory_cli_guided_profile.py',
  ('tests/test_bootstrap_wizard_inventory_cli_guided_profile_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_inventory_cli_guided_binding.py', ('tests/test_wizard_inventory_helpers.py',)),
 ('venus_evcharger/companion/dbus_bridge.py', ('tests/test_venus_evcharger_companion_dbus_bridge.py',)),
 ('venus_evcharger/companion/dbus_bridge_grid.py', ('tests/test_venus_evcharger_companion_dbus_bridge.py',)),
 ('venus_evcharger/companion/dbus_bridge_services.py', ('tests/test_venus_evcharger_companion_dbus_bridge.py',)),
 ('venus_evcharger/control/cli.py', ('tests/test_venus_evcharger_control_cli_contracts.py',)),
 ('venus_evcharger/control/cli_parser.py', ('tests/test_venus_evcharger_control_cli_contracts.py',)),
 ('venus_evcharger/control/docgen.py', ('tests/test_venus_evcharger_control_docgen.py',)),
 ('venus_evcharger/bootstrap/path_defaults.py', ('tests/test_bootstrap_path_defaults.py',)),
 ('venus_evcharger/bootstrap/path_groups.py', ('tests/test_bootstrap_path_groups.py',)),
 ('venus_evcharger/auto/',
  ('tests/test_auto_battery_balance_contracts.py',
   'tests/test_auto_logic_decisions_preaverage.py',
   'tests/test_auto_logic_gates_metrics.py',
   'tests/test_auto_logic_types.py',
   'tests/test_auto_policy_builders.py',
   'tests/test_auto_tracking.py',
   'tests/test_venus_evcharger_auto_policy.py',
   'tests/test_venus_evcharger_auto_controller.py',
   'tests/venus_evcharger_auto_controller_cases_primary.py',
   'tests/venus_evcharger_auto_controller_cases_recovery.py')),
 ('venus_evcharger/inventory/', ('tests/test_device_inventory_config.py', 'tests/test_wizard_inventory_helpers.py')),
 ('venus_evcharger/backend/',
  ('tests/test_backend_config_file.py',
   'tests/test_venus_evcharger_backend_factory.py',
   'tests/test_venus_evcharger_backend_probe.py',
   'tests/test_backend_factory_probe_contracts.py',
   'tests/test_topology_config.py')),
 ('venus_evcharger/bootstrap/', ('tests/test_venus_evcharger_bootstrap_controller.py',)))
