# SPDX-License-Identifier: GPL-3.0-or-later
"""Focused mutmut test selections for optional mutation audits."""

from __future__ import annotations

FOCUSED_TEST_SELECTIONS_BOOTSTRAP: tuple[tuple[str, tuple[str, ...]], ...] = (('venus_evcharger/backend/template_meter_contract.py', ('tests/test_venus_evcharger_backend_template_meter.py',)),
 ('venus_evcharger/backend/template_support_contract.py', ('tests/test_venus_evcharger_backend_template_support.py',)),
 ('venus_evcharger/backend/template_switch_contract.py', ('tests/test_venus_evcharger_backend_template_switch.py',)),
 ('venus_evcharger/backend/tuya_meter.py', ('tests/test_venus_evcharger_backend_tuya.py',)),
 ('venus_evcharger/backend/tuya_switch.py', ('tests/test_venus_evcharger_backend_tuya.py',)),
 ('venus_evcharger/bootstrap/config_auto.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_daytime.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_helper.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_helper_gateway.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_helper_polling.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_helper_resilience.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_sources.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_sources_battery.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_sources_energy.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_sources_grid.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_sources_pv.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_timing.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_timing_audit.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_timing_balance.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_timing_core.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_timing_victron_bias.py', ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_timing_victron_bias_apply.py',
  ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_timing_victron_bias_base.py',
  ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_timing_victron_bias_pid.py',
  ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_auto_timing_victron_bias_safety.py',
  ('tests/test_bootstrap_config_auto_contracts.py',)),
 ('venus_evcharger/bootstrap/config_backend.py',
  ('tests/test_venus_evcharger_bootstrap_controller.py',
   'tests/test_auto_backend_bootstrap_edge_contracts.py')),
 ('venus_evcharger/bootstrap/config_identity.py',
  ('tests/test_venus_evcharger_bootstrap_controller.py',
   'tests/test_auto_backend_bootstrap_edge_contracts.py')),
 ('venus_evcharger/bootstrap/contracts.py', ('tests/test_boundary_port_edge_contracts.py',)),
 ('venus_evcharger/bootstrap/config_shared.py', ('tests/venus_evcharger_bootstrap_controller_config_cases.py',)),
 ('venus_evcharger/bootstrap/controller.py',
  ('tests/test_venus_evcharger_bootstrap_controller.py',
   'tests/test_auto_backend_bootstrap_edge_contracts.py')),
 ('venus_evcharger/bootstrap/runtime.py', ('tests/venus_evcharger_bootstrap_controller_runtime_cases.py',)),
 ('venus_evcharger/bootstrap/runtime_loops.py', ('tests/test_bootstrap_runtime_loops.py',)),
 ('venus_evcharger/bootstrap/runtime_metadata.py', ('tests/test_bootstrap_runtime_metadata.py',)),
 ('venus_evcharger/bootstrap/runtime_virtual_state.py', ('tests/test_bootstrap_runtime_virtual_state.py',)),
 ('venus_evcharger/bootstrap/wizard.py',
  ('tests/test_venus_evcharger_setup_wizard.py',
   'tests/test_venus_evcharger_setup_wizard_extensions.py',
   'tests/test_venus_evcharger_setup_wizard_branch_runtime.py',
   'tests/test_bootstrap_wizard_main.py')),
 ('venus_evcharger/bootstrap/wizard_main.py',
  ('tests/test_venus_evcharger_setup_wizard.py',
   'tests/test_venus_evcharger_setup_wizard_extensions.py',
   'tests/test_venus_evcharger_setup_wizard_branch_runtime.py',
   'tests/test_branch_coverage_next_cluster_six.py',
   'tests/test_bootstrap_wizard_main.py')),
 ('venus_evcharger/bootstrap/wizard_runtime.py',
  ('tests/test_venus_evcharger_setup_wizard.py',
   'tests/test_venus_evcharger_setup_wizard_extensions.py',
   'tests/test_venus_evcharger_setup_wizard_branch_runtime.py',
   'tests/test_bootstrap_wizard_runtime_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_runtime_energy.py',
  ('tests/test_venus_evcharger_setup_wizard.py',
   'tests/test_venus_evcharger_setup_wizard_extensions.py',
   'tests/test_bootstrap_wizard_runtime_contracts.py',
   'tests/test_bootstrap_wizard_runtime_energy_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_runtime_live.py',
  ('tests/test_venus_evcharger_setup_wizard_branch_runtime.py',
   'tests/test_bootstrap_wizard_runtime_contracts.py',
   'tests/test_bootstrap_wizard_runtime_live_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_runtime_persistence.py',
  ('tests/test_venus_evcharger_setup_wizard_branch_runtime.py',
   'tests/test_bootstrap_wizard_runtime_contracts.py',
   'tests/test_bootstrap_wizard_runtime_persistence_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_runtime_write.py',
  ('tests/test_venus_evcharger_setup_wizard_branch_runtime.py',
   'tests/test_bootstrap_wizard_main.py',
   'tests/test_bootstrap_wizard_runtime_write_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_runtime_results.py',
  ('tests/test_bootstrap_wizard_runtime_results_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_support.py',
  ('tests/test_venus_evcharger_setup_wizard_branch_coverage.py',
   'tests/test_bootstrap_wizard_support_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_topology.py',
  ('tests/test_bootstrap_wizard_topology_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_topology_render.py',
  ('tests/test_bootstrap_wizard_topology_render_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_transport_guidance.py',
  ('tests/test_bootstrap_wizard_transport_guidance_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_adapters.py',
  ('tests/test_venus_evcharger_setup_wizard.py',
   'tests/test_venus_evcharger_setup_wizard_extensions.py',
   'tests/test_venus_evcharger_setup_wizard_branch_coverage.py',
   'tests/test_bootstrap_wizard_adapters_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_capacity.py',
  ('tests/test_venus_evcharger_setup_wizard_branch_runtime.py',
   'tests/test_branch_coverage_next_cluster_six.py',
   'tests/test_bootstrap_wizard_capacity.py')),
 ('venus_evcharger/bootstrap/wizard_charger_presets.py',
  ('tests/test_venus_evcharger_setup_wizard_branch_coverage.py', 'tests/test_bootstrap_wizard_charger_presets.py')),
 ('venus_evcharger/bootstrap/wizard_inventory',
  ('tests/test_bootstrap_wizard_inventory_contracts.py',
   'tests/test_bootstrap_wizard_inventory_editor_contracts.py',
   'tests/test_bootstrap_wizard_inventory_editor_bindings_contracts.py',
   'tests/test_bootstrap_wizard_inventory_cli_actions_contracts.py',
   'tests/test_bootstrap_wizard_inventory_cli_contracts.py',
   'tests/test_bootstrap_wizard_inventory_cli_guided_binding_contracts.py',
   'tests/test_bootstrap_wizard_inventory_cli_guided_common_contracts.py',
   'tests/test_bootstrap_wizard_inventory_cli_guided_profile_contracts.py',
   'tests/test_bootstrap_wizard_inventory_cli_payload_contracts.py',
   'tests/test_bootstrap_wizard_inventory_prompts_contracts.py',
   'tests/test_bootstrap_wizard_inventory_support_contracts.py',
   'tests/test_wizard_inventory_helpers.py',
   'tests/test_wizard_inventory_helpers_part2.py',
   'tests/test_wizard_inventory_helpers_part3.py')),
 ('venus_evcharger/bootstrap/wizard_layouts.py', ('tests/test_bootstrap_wizard_layouts_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_policy_guidance.py',
  ('tests/test_bootstrap_wizard_policy_guidance_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_persistence.py',
  ('tests/test_branch_coverage_next_cluster_five.py',
   'tests/test_bootstrap_wizard_persistence_contracts.py')),
 ('venus_evcharger/bootstrap/wizard_render_backends.py',
  ('tests/test_bootstrap_wizard_render_backends_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_render_defaults.py',
  ('tests/test_bootstrap_wizard_render_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_render_io.py',
  ('tests/test_bootstrap_wizard_render_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_render_live.py',
  ('tests/test_bootstrap_wizard_render_contracts.py',
   'tests/test_branch_coverage_hotspots_part6.py')),
 ('venus_evcharger/bootstrap/wizard_render_secrets.py',
  ('tests/test_bootstrap_wizard_render_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_render_text.py',
  ('tests/test_bootstrap_wizard_render_text_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_render.py',
  ('tests/test_bootstrap_wizard_render_contracts.py',)),
 ('venus_evcharger/bootstrap/wizard_review.py',
  ('tests/test_bootstrap_wizard_review_contracts.py',)))
