# SPDX-License-Identifier: GPL-3.0-or-later
"""Type contracts shared by diagnostic publishing mixins."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Callable, TYPE_CHECKING


DiagnosticValue = str | int | float


class _DbusDiagnosticsContractsMixin:
    """Declare sibling-mixin helpers used by diagnostic publishers."""

    service: Any
    _age_seconds: Callable[[Any, float], float]

    if TYPE_CHECKING:

        def _backend_mode_value(self, service: Any) -> str: ...

        def _backend_type_value(self, service: Any, attribute_name: str, default: str = "") -> str: ...

        def _charger_text_observed(self, attribute_name: str) -> str: ...

        def _charger_estimate_active(self) -> int: ...

        def _charger_estimate_source(self) -> str: ...

        def _charger_transport_active(self, now: float) -> int: ...

        def _charger_transport_reason(self, now: float) -> str: ...

        def _charger_transport_source(self, now: float) -> str: ...

        def _charger_transport_detail(self, now: float) -> str: ...

        def _charger_retry_active(self, now: float) -> int: ...

        def _charger_retry_reason(self, now: float) -> str: ...

        def _charger_retry_source(self, now: float) -> str: ...

        def _charger_current_target_value(self, service: Any) -> float: ...

        def _auto_phase_metric_text(self, service: Any, field_name: str) -> str: ...

        def _auto_phase_metric_float(self, service: Any, field_name: str) -> float: ...

        def _observed_phase_value(self, service: Any) -> str: ...

        def _phase_switch_mismatch_active(self, service: Any) -> int: ...

        def _phase_switch_lockout_active(self, service: Any, now: float) -> int: ...

        def _phase_switch_lockout_target(self, service: Any, now: float) -> str: ...

        def _phase_switch_lockout_reason(self, service: Any, now: float) -> str: ...

        def _phase_supported_configured(self, service: Any) -> str: ...

        def _phase_supported_effective(self, service: Any, now: float) -> str: ...

        def _phase_degraded_active(self, service: Any, now: float) -> int: ...

        def _switch_feedback_closed(self, service: Any) -> int: ...

        def _switch_interlock_ok(self, service: Any) -> int: ...

        def _switch_feedback_mismatch(self, service: Any) -> int: ...

        def _contactor_suspected_open(self, service: Any) -> int: ...

        def _contactor_suspected_welded(self, service: Any) -> int: ...

        def _contactor_fault_count(self, service: Any) -> int: ...

        def _contactor_lockout_active(self, service: Any) -> int: ...

        def _contactor_lockout_reason(self, service: Any) -> str: ...

        def _contactor_lockout_source(self, service: Any) -> str: ...

        def _auto_metrics(self, service: Any) -> dict[str, Any]: ...

        def _scheduled_snapshot(self, service: Any, now: float) -> Any: ...

        def _fault_reason(self, service: Any) -> str: ...

        def _recovery_active(self, service: Any) -> int: ...

        def ensure_state(self) -> None: ...

        def _publish_values_transactional(
            self,
            group_name: str,
            values: Mapping[str, Any],
            now: float | None,
            interval_seconds: float | None = None,
            force: bool = False,
        ) -> bool: ...
