# SPDX-License-Identifier: GPL-3.0-or-later
"""Canonical field inventory and initial state for helper snapshots."""

from __future__ import annotations

import os

from venus_evcharger.core.shared import AUTO_INPUT_SNAPSHOT_SCHEMA_VERSION
from venus_evcharger.inputs.helper.contracts import Snapshot

BATTERY_SNAPSHOT_FIELDS = (
    "battery_soc",
    "battery_combined_soc",
    "battery_combined_usable_capacity_wh",
    "battery_combined_charge_power_w",
    "battery_combined_discharge_power_w",
    "battery_combined_net_power_w",
    "battery_combined_ac_power_w",
    "battery_combined_pv_input_power_w",
    "battery_combined_grid_interaction_w",
    "battery_headroom_charge_w",
    "battery_headroom_discharge_w",
    "expected_near_term_export_w",
    "expected_near_term_import_w",
    "battery_discharge_balance_mode",
    "battery_discharge_balance_target_distribution_mode",
    "battery_discharge_balance_error_w",
    "battery_discharge_balance_max_abs_error_w",
    "battery_discharge_balance_total_discharge_w",
    "battery_discharge_balance_eligible_source_count",
    "battery_discharge_balance_active_source_count",
    "battery_discharge_balance_control_candidate_count",
    "battery_discharge_balance_control_ready_count",
    "battery_discharge_balance_supported_control_source_count",
    "battery_discharge_balance_experimental_control_source_count",
    "battery_average_confidence",
    "battery_source_count",
    "battery_online_source_count",
    "battery_valid_soc_source_count",
    "battery_battery_source_count",
    "battery_hybrid_inverter_source_count",
    "battery_inverter_source_count",
    "battery_sources",
    "battery_learning_profiles",
)


def empty_snapshot(captured_at: float | None = None) -> Snapshot:
    """Return the complete initial helper snapshot contract."""
    return {
        "snapshot_version": AUTO_INPUT_SNAPSHOT_SCHEMA_VERSION,
        "snapshot_sequence": 0,
        "captured_at": captured_at,
        "captured_monotonic": captured_at,
        "heartbeat_at": captured_at,
        "heartbeat_monotonic": captured_at,
        "writer_pid": os.getpid(),
        "helper_state": "starting",
        "helper_status": "starting",
        "pv_status": "missing",
        "pv_captured_at": None,
        "pv_observed_monotonic": None,
        "pv_power": None,
        "battery_status": "missing",
        "battery_captured_at": None,
        "battery_observed_monotonic": None,
        "battery_soc": None,
        "battery_combined_soc": None,
        "battery_combined_usable_capacity_wh": None,
        "battery_combined_charge_power_w": None,
        "battery_combined_discharge_power_w": None,
        "battery_combined_net_power_w": None,
        "battery_combined_ac_power_w": None,
        "battery_source_count": 0,
        "battery_online_source_count": 0,
        "battery_valid_soc_source_count": 0,
        "battery_sources": [],
        "battery_learning_profiles": {},
        "grid_status": "missing",
        "grid_captured_at": None,
        "grid_observed_monotonic": None,
        "grid_power": None,
        "grid_gateway_captured_at": None,
        "grid_gateway_observed_monotonic": None,
        "grid_gateway_power": None,
        "grid_primary_captured_at": None,
        "grid_primary_power": None,
        "grid_fusion_enabled": False,
        "grid_fusion_primary_source_id": "",
        "grid_fusion_backup_source_id": "victron",
        "grid_selected_source_id": "",
        "grid_fusion_state": "unavailable",
        "grid_fusion_confidence": 0.0,
        "grid_fusion_primary_valid": False,
        "grid_fusion_backup_valid": False,
        "grid_fusion_primary_age_seconds": None,
        "grid_fusion_backup_age_seconds": None,
        "grid_fusion_difference_watts": None,
        "grid_fusion_tolerance_watts": None,
        "grid_fusion_primary_invalid_samples": 0,
        "grid_fusion_primary_recovery_samples": 0,
        "grid_fusion_mismatch_samples": 0,
    }
